### PR TITLE
Fix path resolution on PS 5 and lower

### PR DESCRIPTION
**Pull request by kborowinski**
@dfinke Fixes issue #89.

The other changes are the whitespace cleanup, this is done automatically by VSCode on save. Hope you don't mind it.

### CODE REVIEW

**Comment by dfinke** [comment]
Thank you. I am right now in the middle of refactoring all this. Using GPT-4 and dialing in on the interaction with the model. I will leave this open. We'll see what makes it to the new approach.

**Comment by dfinke** [comment]
Could you open another PR and add that to the `Get-GPT3Completion` function?

**Comment by kborowinski** [comment]
> Could you open another PR and add that to the `Get-GPT3Completion` function?

You want me to move following code from `Get-ChatCompletion` to the `Get-GPT3Completion` function?
```powershell
$Script:chatSessionPath = if ($PSVersionTable.PSVersion.Major -lt 6 -or $IsWindows) {
    Join-Path $env:APPDATA 'PowerShellAI/ChatGPT'
} else {
    Join-Path $env:HOME '~/PowerShellAI/ChatGPT'
}
```
I don't quite follow 🤷‍♂️

**Comment by dfinke** [comment]
Never mind. I was thinking it was a different piece of code. I've got a bunch refactored and will include this in the new function. Thank you.

**Pull request closed without merging**
