### PR TITLE
Adding Write-OpenAIFunction (Fixes #53)

### LINKED ISSUE #53: Write-OpenAIFunction
In order to make it easy to build atop of PowerShellAI, it should be simple to write an OpenAI function.

This command should take a -Prompt parameter and turn any PowerShell variables within it into parameters.

## Examples 

~~~PowerShell
Write-OpenAIFunction -Prompt {
    "Write a recipe based on these ingredients and instructions: $Ingredients"
}
~~~

Should produce something like:

~~~PowerShell

function Write-Recipe {
     param(
     $Ingredients
     )
     $myPrompt = $executionContext.InvokeCommand.ExpandString(
         "Write a recipe based on these ingredients and instructions: $Ingredients"
     )
     ai $myPrompt     
}
~~~

~~~PowerShell
. (Write-OpenAIFunction -Prompt "Get Planets Name, Mass, Diameter, Distance (in AU) as JSON numbers" -AIParameter @{max_tokens=2kb} -ForeachObject {$_ | ConvertFrom-JSON })

Get-Planets # Will now return data!
~~~

## It Should

* [ ] Allow a Variable followed immediately by ? to be optional
* [ ] Infer the -Verb and -Noun if none is provided
* [ ] Infer the -Synopsis and -Description if none is provided
* [ ] Infer -ParameterHelp @{} if not provided
* [ ] Allow -Examples to be added
* [ ] Allow a custom -Begin or -End
* [ ] Allow a -ForeachObject, to pipe AI results into something
* [ ] Allow the -AICommand to be customized (for, say, making images instead of getting text)
* [ ] Allow -AIParameter(s) to be provided (for, say, changing max tokens)
* [ ] Return a [ScriptBlock] (for easy embedding, dynamic execution, and transpilation)

### PR DESCRIPTION
**Pull request by StartAutomating**

### CODE REVIEW

**Comment by dfinke** [comment]
lol, you can't help yourself throwing in the kitchen sink. 

Thanks for the PR

**Comment by StartAutomating** [comment]
> lol, you can't help yourself throwing in the kitchen sink.

1. Do it right instead of do it twice.
2. I _really_ wanted to ship with less, but making Get-Planets return an actual object made me add -AIParameter as well.

I can't currently think of too much it might need at this point (though if you want some changes lemme know).

Significant bonus points:

This also lets me transpile this part of PowerShellAI:

~~~PowerShell
Install-Module PipeScript -Scope CurrentUser -Force
Import-Module PipeScript
{ 
[Write_AIFunction(prompt='What is best in life?',noun='Best')]$null
}.Transpile()
~~~

**Comment by dfinke** [comment]
You have no clue if it is right. There are no scenarios yet. Just text replacement 😂

**Comment by StartAutomating** [comment]
> You have no clue if it is right.

?  The examples I have I have tested.   Let me know if you want me to add some Pester tests.

> There are no scenarios yet. Just text replacement 😂

We're you saying that prompt engineering was a thing?  Why not give a tool to help people engineer a prompt?

**Comment by dfinke** [comment]
That’s the plan. Not sure your function is how want to solve it. Need to think about it. My tweet in this was not about this. My tweet was just off the top of my head. 

Will close and put in the backlog

**Pull request closed without merging**
