### PR TITLE
Add ability to get/set OpenAI base URI.

### PR DESCRIPTION
**Pull request by AjayKMehta**
This addresses https://github.com/dfinke/PowerShellAI/issues/158.

1. Add new cmdlets to get and set OpenAI base URI (default value is `https://api.openai.com`).
2. Modified `Get-LocalOpenAIKey` to retrieve value of environment variable `OPENAI_API_KEY`.
3. Minor formatting + linting changes.

### CODE REVIEW

**Comment by dfinke** [comment]
Thank you! Wow, that required a bunch of updates in a bunch of places.

Thanks for dotting the i's and crossing the t's. Tests, comment based help etc.

I need to carve out time to take it through it's paces.

Thank you again!

**Comment by AjayKMehta** [comment]
You're welcome. I am glad to contribute and give back to such a great module!

I noticed that my VS Code settings for PowerShell led to some formatting changes: trimmed whitespace and changed double quotes to single quotes for strings. 

This gave me the idea of adding a [PSScriptAnalyzer settings file](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#settings-support-in-scriptanalyzer) to the module to enforce a common coding style. Also, we can create a GitHub workflows to fix/check style on push or PR. If OK with you, I can create a separate PR for this.

**Comment by dfinke** [comment]
Yeah, I saw that changes happened to files. figured whitespace and formatting.

A separate PR for those rules would be great. I haven't setup an analyzer for that, be interested to see.
Also, if not too much trouble. A separate PR for the GHA. Would like to see that.

My concern, just off the top of my head, is too much automation like this can cause issues that are tough to debug.

**Comment by AjayKMehta** [comment]
I will submit a PR for the rules this weekend. 

I prefer to run linters (along with tests) locally before pushing commits as I don't like the idea of the CICD process modifying code either.

**Comment by dfinke** [comment]
@AjayKMehta, to confirm, where would the `preview` live on the gallery? Your Artifactory can pull it form there?

**Comment by AjayKMehta** [comment]
I just tried installing pre-release version of PSReadline from Artifactory and it worked 😀

**Comment by dfinke** [comment]
@AjayKMehta, curious should `Get-OpenAIBaseURI` be used over `${Script:OpenAIBaseUri}` in `Get-OpenAIBaseRestURI.ps1`?

Plus a few others in the PR.

Also, did you make a sweep of the functions to see if this was needed elsewhere?

**Comment by AjayKMehta** [comment]
1. I  chose to use `${script:OpenAIBaseUri}` over `Get-OpenAIBaseURI`  because the the latter just returns the former and wanted to avoid indirection. I can change it if you think it makes sense.

2. Yes, I did a sweep by searching for `https://api.openai.com` and replacing occurrences with `${script:OpenAIBaseUri}` .

**Comment by dfinke** [comment]
Using `Get-OpenAIBaseURI` keeps the code "Don't Repeat Yourself" (DRY). Also, if additional processing is needed, maybe logging, it can be done in one place.

- Please add a test for the check of the URI last char
- Please update to use `Get-OpenAIBaseURI`

**Comment by AjayKMehta** [comment]
@dfinke , addressed your feedback with latest commits.

**Comment by dfinke** [comment]
Thank you for making the updates! They look good. I'm out of town till Fri. Will publish as a pre-release when back.

**Pull request closed without merging**
