### PR TITLE
Usage

### PR DESCRIPTION
**Pull request by stefanstranger**
Created a Polyglot Notebook to get OpenAI User information calling the OpenAI REST API.

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks @stefanstranger.

May have missed it. These endpoints look like they'd be a good addition to the core module.
Thoughts?

**Comment by dfinke** [comment]
Hi @stefanstranger, I added some cells to the nb.
I used these functions `Get-OpenAIBaseRestURI` `Invoke-OpenAIAPI`.

`Invoke-OpenAIAPI` already does what you do with the header, convert-fromJson etc.

Happy to revert my changes.

Let me know what you think.

**Comment by stefanstranger** [comment]
> Thanks @stefanstranger.

May have missed it. These endpoints look like they'd be a good addition to the core module.
Thoughts? 

I had not checked the core module to be honest, but sure add them if you think they are useful. I used the Edge Browser Developer tools to see if there are any interesting APIs to use :-)

**Comment by stefanstranger** [comment]
> Hi @stefanstranger, I added some cells to the nb.
I used these functions `Get-OpenAIBaseRestURI` `Invoke-OpenAIAPI`.

`Invoke-OpenAIAPI` already does what you do with the header, convert-fromJson etc.

Happy to revert my changes.

Let me know what you think. 

Missed the  `Get-OpenAIBaseRestURI` `Invoke-OpenAIAPI` functions but yes if these are already present those should be used instead of the plain rest api calls I used.

**Comment by dfinke** [comment]
I like what you did, plus the notebook.

Be great if the rest endpoints you showed were in the psm1.

Total yours if you want to add that and tests. 

Have credit for making the module even better.

No worries if not.

**Comment by stefanstranger** [comment]
Do you want me to update the notebook using the  `Get-OpenAIBaseRestURI` `Invoke-OpenAIAPI` functions?

I'll have a look at the psm1 to see how to add the rest endpoints.

**Comment by stefanstranger** [comment]
Please review the new 'core' functions I added. Let me know if you have questions.

**Comment by dfinke** [comment]
Terrific! Do you know if there are other endpoints for the dashboard besides these?

**Comment by dfinke** [comment]
@stefanstranger Thank you!

**Comment by stefanstranger** [comment]
If I find more 'hidden' apis I'll let you know.

**Pull request merged**
