### PR TITLE
Add error insights

### PR DESCRIPTION
**Pull request by ShaunLawrie**
The prompt could use some work but the idea holds up.
This adds a simple example of using your module to inspect the last error record and offer some suggestions on how to resolve it.  

image

### CODE REVIEW

**Comment by dfinke** [comment]
That's great! Thanks for the PR! Lots of opportunity along these lines.

Wondering of this should be in the module itself?

I like the name `Get-ErrorInsights` and would prefer `AI` or `OpenAI` in it. That way someone/I can do `gcm *-openai*`.

Thanks for adding an interactive notebook too, that's great! 👍

Let me know what you think. I'll merge it shortly.

**Comment by shaun-lawrie-ptml** [comment]
If it fits with the modules direction feel free to move the function into the core and rename it. Then this can just be the example notebook.

Thanks for the work you've already done Doug. I was thinking of doing this error introspection as a stand-alone module but it doesn't really make sense when your module does all the hard work of interfacing with the openai APIs already.

**Comment by dfinke** [comment]
Cool. I'll percolate on the name.

Please could you add a little comment-based help? One example may be doable.
Also, please could you add the image here to the `/media ` folder. I'll incorporate it into the README.

- Thank you!

**Comment by dfinke** [comment]
## That is cool

Need to move this to the psm1. 

@shaun-lawrie-ptml  nicely played!

image

**Comment by dfinke** [comment]
Thoughts on these, or come up with others:

- Get-GPTSolution
- Get-ErrorGPTSolution
- Get-ErrorResolution
- Find-ErrorResolutionGPT
- Find-ErrorResolution
- Invoke-AIErrorHelper

**Comment by ShaunLawrie** [comment]
I shifted it into the main module. I'm not sure how you were planning on writing it into the readme so I'll leave that up to you 👍

**Comment by dfinke** [comment]
Thanks for moving! I'll check it out.

**Comment by dfinke** [comment]
I added an `ieh` alias. Not sure if it is the best.
Makes quick work of it!

image

**Comment by dfinke** [comment]
@shaun-lawrie-ptml Thanks for the addition! I like the angle you took.

**Pull request merged**
