### PR TITLE
added function

### PR DESCRIPTION
**Pull request by Skatterbrainz**
Added a function to return available models

### CODE REVIEW

**Comment by dfinke** [comment]
This is great! I had a `get-models` early on. This makes me think the `invoke-restmethod` repeats itself and I/We should "centralize" it. 

Also, did you update the psd1 to export those functions?

**Comment by Skatterbrainz** [comment]
Doh! I forgot the .psd1 update. Doing that now.

**Comment by dfinke** [comment]
Sorry, would it be possible for you to change over and use `Test-OpenAIKey`? 

It's time to refactor the rest calls and DRY (do not repeat yourself) up the code and add tests.

ChatGPT is coming online with a REST API, so that would create more sprawl.

Thanks!

**Comment by dfinke** [comment]
@Skatterbrainz Thanks for the functions. They kicked up the refactoring. You can checkout the updated version in the main branch. Feel free to make more PRs. Saved me a whole bunch of time. Thanks again!

**Comment by Skatterbrainz** [comment]
Sorry for the slow reply - I was on travel (moving our son to Nashville) and just got home tonight. Thank you!

**Comment by dfinke** [comment]
@Skatterbrainz no worries. Thanks for PR and doing the leg work. Nice, Nashville sounds like fun.

**Pull request closed without merging**
