### PR TITLE
Add error handling; Update and fix help; Remove whitespaces; Minor code refactoring

### PR DESCRIPTION
**Pull request by kborowinski**
This PR adds error handling to allow users to use *PowerShellAI* in own scripts or non-interactive scenarios.

In addition following changes were made:
- fixed punctuation in help
- added missing parameters in help
- minor code refactoring
- extra whitespaces are removed

@dfinke: Please review add comments on anything you would like to change

### CODE REVIEW

**Comment by dfinke** [comment]
@kborowinski Thank you! 

Did you see I started a discussion https://github.com/dfinke/PowerShellAI/discussions/64

Would love your feedback before we proceed.

Your updates are great!

**Comment by kborowinski** [comment]
@dfinke I didn't have a chance to look at it yet but will do tomorrow. Thanks for merging my PR BTW.

Ps. I think that we badly need to add more tests. I've been burned a few times already on my own mistakes 😅

**Comment by dfinke** [comment]
@kborowinski All good, that's how we learn 😆

My assumptions are, and that could be a bad thing, is we are professionals in what we do. The PR list isn't that big.
I love interacting with community, it helps me, them and everyone.

Folks need to review it before going heads down creating code.

**Comment by kborowinski** [comment]
Yeah, mocking with couple of test cases with real or fake REST responses should be enough. As for the rest, we should test the parameters and error handling.

**Comment by dfinke** [comment]
Agreed on the param and error testing.

It may best to hold off on that a bit. There is some churn still to come.

I don't like the choice, may cause re-writing as tests are implemented. 

Side effect of playing with new tech and APIs 🙂

**Comment by dfinke** [comment]
Thanks for the PR. Will revisit.

**Pull request closed without merging**
