### PR TITLE
Fix tests to run in StrictMode and on PS 5.1

### PR DESCRIPTION
**Pull request by kborowinski**
This fixes issue #98 ~~with following caveat on *PS 5.1* where test `Get-ChatSessionContent returns correct content` fails *probably* due to a legitimate error and needs further investigation~~ *(EDIT: also fixed, check below)*:
ps51

Fixed the `Get-ChatSessionContent returns correct content` test. On PS 5.1 property alias `[Alias('FullName')]` is used for binding **ONLY** when passing path with pipeline therefore [we need to extract `FullName` property](https://github.com/dfinke/PowerShellAI/blob/e0700d97493e5b5157e4c90d6325e303bd59c079/__tests__/SessionManagement.tests.ps1#L201). This is fixed on PS 6 and higher.
image

PS 7.3
ps73

### CODE REVIEW

**Comment by dfinke** [comment]
Thank you! I need to update the GitHub Action so it can uncover these sorts of issues.

**Comment by kborowinski** [comment]
> Thank you! I need to update the GitHub Action so it can uncover these sorts of issues.

You would need docker with PS 5.1, right?

**Comment by dfinke** [comment]
Maybe. I had setup Windows PS v5.1 testing but it was on Azure devops. 
I'd prefer to stay away from containers, unless it is the only way.
Need to research.

**Comment by dfinke** [comment]
I'm not comfortable with passing the `.FullName`. I have not had time to look at the issue and have been on v7.x for way to long to know how to directly handle this in v5.1 etc. I vaguely remember using `$LiteralPath` instead of `$Path` and then doing the alias. Don't remember but I'd prefer a simpler solution, not sure what it is.

**Comment by kborowinski** [comment]
> I'm not comfortable with passing the `.FullName`. I have not had time to look at the issue and have been on v7.x for way to long to know how to directly handle this in v5.1 etc. I vaguely remember using `$LiteralPath` instead of `$Path` and then doing the alias. Don't remember but I'd prefer a simpler solution, not sure what it is.

`$LiteralPath` won't cut it, but I will look into it. Do you prefer another PR fixing this or can I include the fix in thisPR?

**Comment by kborowinski** [comment]
@dfinke:
1. I've refactored [Get-ChatSessionContent](https://github.com/dfinke/PowerShellAI/pull/99/commits/6ec8e10a5d0cbcf0a72b9eb21b77900cf42e92ac) to work correctly on PS5.1 without the need to pass `.FullName`
2.  I've added [test](https://github.com/dfinke/PowerShellAI/pull/99/commits/805aff6154f5f4643a7853df097c83a68b1cce20) to make sure that `Get-ChatSessionContent` does not throw on null path
3. Other changes are to cast object to array just before checking `.Count` property and not directly on the result

**Comment by dfinke** [comment]
Thanks. I tried it on v5.1 and it seems to work.

```
Get-ChatSessionContent C:\Users\finke\AppData\Roaming\PowerShellAI\ChatGPT\20230403103924-ChatGPTSession.xml
```

```
Get-ChatSession | select -last 1  | Get-ChatSessionContent
```

First order for me is to add to the GHA so I can test multiple PS versions, on all OSes.

Once that surfaces errors, we can figure out a better way to solve, it'll have a better safety net.

Thanks for finding these!

**Comment by dfinke** [comment]
Thanks for the PR. Will revisit.

**Pull request closed without merging**
