### PR TITLE
wip - investigate using Write-Codeblock

### PR DESCRIPTION
**Pull request by dfinke**
@ShaunLawrie 
- Do I need to pass the code to ScriptAnalyzer to "autoformat"?
- Does `Write-Codeblock` handle that?
- For the "menu" is that reusable? Can I pipe Write-Codeblock to it and it appends the choices?

```powershell
copilot 'write a function to greet'
```

image

### CODE REVIEW

**Comment by shaun-lawrie-ptml** [comment]
I used scriptanalyzer to auto format and fix indentation that chatGPT generated but that's optional. Write-CodeBlock purely just writes what you give it, it doesn't format it.

Having -ShowLineNumbers turned on makes it not copy-paste-able because is includes the line number when you copy btw.

**Comment by ShaunLawrie** [comment]
I used scriptanalyzer to auto format and fix indentation that chatGPT generated but that's optional. Write-CodeBlock purely just writes what you give it, it doesn't format it.

Having -ShowLineNumbers turned on makes it not copy-paste-able because is includes the line number when you copy btw.

**Comment by dfinke** [comment]
Good to know. I want to use your choice options A-Z. keep it DRY.

Is that part a function?

**Comment by dfinke** [comment]
Thanks @ShaunLawrie! `Invoke-Formatter` FTW!

image

**Comment by ShaunLawrie** [comment]
You mean this? https://github.com/dfinke/PowerShellAI/blob/1ae724f21a40e1d3a71a0fe7d9d91290d2d8a641/Private/FunctionBuilderCore.ps1#L54

I pretty hackily implemented handling the options in https://github.com/dfinke/PowerShellAI/blob/1ae724f21a40e1d3a71a0fe7d9d91290d2d8a641/Public/Invoke-AIFunctionBuilder.ps1#L85

The “run” approach I’m not happy with but I needed something that worked.

You just have to make sure to check if scriptanalyzer is available on the users machine to use invoke-formatter. It’s a bit expensive to get-command every time so I wrapped it with a cached script variable https://github.com/dfinke/PowerShellAI/blob/1ae724f21a40e1d3a71a0fe7d9d91290d2d8a641/Private/FunctionBuilderParser.ps1#L51

**Comment by dfinke** [comment]
Awesome! Thanks.

**Comment by ShaunLawrie** [comment]
I’d be keen to hear if there’s a better solution to using a module to import the functions into the current session, I used ipmo -global so the function could be accessed from the users terminal session after the script ran.

**Comment by dfinke** [comment]
One benefit, variable scoping.

**Comment by dfinke** [comment]
Might be good as a function. Saving where the module is, I like the convenience, not sure if should be generalized.

I'm selfish, could reuse this in `copilot`.

https://github.com/dfinke/PowerShellAI/blob/c93ce07696cac9f706631e5ea92c9de21af2adef/Public/Invoke-AIFunctionBuilder.ps1#L86-L167

**Pull request merged**
