### PR TITLE
added edits api functions

### PR DESCRIPTION
**Pull request by Skatterbrainz**

### CODE REVIEW

**Comment by dfinke** [comment]
Nice! Could you add a test for the Uri in `OpenAIUri.tests.ps1` - Thank you

**Comment by dfinke** [comment]
@Skatterbrainz are those models the only ones the `edit` work in?

**Comment by dfinke** [comment]
## Sweet
image

**Comment by Skatterbrainz** [comment]
The docs show only 2 models supported, which I missed during my first hour of hair-pulling. :(  The use-case may be limited for this function (practically) but I figured it couldn't hurt to add it.

**Comment by dfinke** [comment]
All good. Those models should be fine. They are tuned for different things. I stayed away from specifying models in a validate set because I didn't want to be the bottleneck when they change.

I also didn't create a dynamic parameter to look them up (like using your `Get-OpenAIModel`) because I thought it would be too slow and expensive.

Thanks again for doing all the legwork in this.

**Pull request merged**
