### PR TITLE
Update Get-GPT3Completion.ps1

### PR DESCRIPTION
**Pull request by MartynKeigher**
Quality of life tweaks: Added alias 'gpt', and added progress indicator while function processes GPT request.

### CODE REVIEW

**Comment by MartynKeigher** [comment]
Just noticed a typo in my 'Write-Progress' line... `repsonse`. needs correcting.

**Comment by dfinke** [comment]
@MartynKeigher Did you check to see if the write-progress works ok with the PSReadLineKeyHandler?

**Comment by MartynKeigher** [comment]
I did not as I’m not well versed in it.

**Comment by dfinke** [comment]
I had tried that, had issues, not sure if is was how I set it up. Was going to ask Twitter how `progress` can be done from a handler

**Comment by dfinke** [comment]
@MartynKeigher thanks for the PR! Made some tweaks.

**Pull request merged**
