### PR TITLE
PowerShellAI shortcut key fix

### LINKED ISSUE #58: AIShortcutKey should be customizable (CTRL+G is taken in VSCode)
When trying out Enable-AIShortCutKey in Visual Studio Code, I noticed that the shortcut key didn't work.  It brought up "goto".

Tweaking the code slightly, I was able to find a shortcut key that I think works "ALT+P".

It would be nice if Enable-AIShortCutKey allowed you to choose the shortcut key (you could find the shortcut key by function name when disabling it).

It would also be nice if the default was the same across both VSCode and Terminal, for the sake of all of our muscle memory.

### PR DESCRIPTION
**Pull request by StartAutomating**
Fixes #58

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks for the PR! Congratulations your first one! 🎉

**Comment by dfinke** [comment]
btw, when you add something to a library that wasn't there, it's an "enhancement", not a "fix". Nothing was broken 🙂

**Comment by StartAutomating** [comment]
@dfinke thanks for taking it!

I use "fixes" in commit message because that will automatically close issues when a PR is merged.
Do you know if `enhancements` will do the same?

**Comment by dfinke** [comment]
you have fix in the PR header. That's what I was referring to.

**Pull request merged**
