### PR TITLE
Add OpenAIModel script parameter

### LINKED ISSUE #101: ai function is always using the default model
The `ai` function is invoking `Get-GPT3Completion` without specifying the `-model` parameter, so it always using the default model - currently `text-davinci-003`.

It can be useful to have ability to set different model for use with `ai`.

## Proposed Approach

Since `ai` is very useful shorthand, adding a parameter for model would be undesirable. Instead, proposing to specify different default model for `ai` (and `Get-GPT3Completion`) using either `$env:OpenAIModel`, or by invoking `Set-OpenAIModel` - similar to handling the OpenAI API key. 

That will allow using existing scripts with different models, without modufications and in non-breaking manner.

### PR DESCRIPTION
**Pull request by SP3269**
This allows specifying model used by the `ai` and `Get-GPT3Completion`.

Resolves #101

### CODE REVIEW

**Comment by dfinke** [comment]
Thank you! I like the notion of a "global" OpenAIModel. I would've have added `-model` to the `ai` function (and others).
Global may be simpler since `get-gpt3completion` could use it.

Concerns:
- This needs tests
- Discoverability can only be done through documentation
  - Not a show stopper, just more work

**Comment by SP3269** [comment]
No worries! Pushed unit tests to the PR. Also, proposed update in the README.

Note that if chat model such as `gpt-4` is specified, `ai` errors out with `This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?`. Haven't found the way to list text models only...

**Comment by dfinke** [comment]
Looks like Linux had an issue with the test.

***Note***: I am prioritizing adding GHA for testing against v5.1 across OSes. These images come with `core`. So there may be more things to sort out shortly.

Thank you again @SP3269 for the PR!

**Comment by dfinke** [comment]
Off the top of my head, makes sense. May look different in the morning :-)

**Comment by SP3269** [comment]
I'm struggling to replace the call to `Get-OpenAIModel` with one to mocked function in the imported module in the test. I'm trying things along these lines:
```powershell
    BeforeEach {
        InModuleScope 'PowerShellAI' {
            # Mock the Get-OpenAiModel function
            function Get-OpenAIModel {
                $data = '["davinci","text-davinci-edit-001","babbage-code-search-code","text-similarity-babbage-001","code-davinci-edit-001","text-davinci-001","ada","babbage-code-search-text","babbage-similarity","whisper-1","code-search-babbage-text-001","text-curie-001","code-search-babbage-code-001","text-davinci-003","text-ada-001","text-embedding-ada-002","text-similarity-ada-001","curie-instruct-beta","ada-code-search-code","ada-similarity","code-search-ada-text-001","text-search-ada-query-001","davinci-search-document","ada-code-search-text","text-search-ada-doc-001","davinci-instruct-beta","text-similarity-curie-001","code-search-ada-code-001","ada-search-query","text-search-davinci-query-001","curie-search-query","gpt-3.5-turbo-0301","davinci-search-query","babbage-search-document","ada-search-document","text-search-curie-query-001","text-search-babbage-doc-001","gpt-3.5-turbo","curie-search-document","text-search-curie-doc-001","babbage-search-query","text-babbage-001","gpt-4","text-search-davinci-doc-001","gpt-4-0314","text-search-babbage-query-001","curie-similarity","curie","text-similarity-davinci-001","text-davinci-002","davinci-similarity","cushman:2020-05-03","ada:2020-05-03","babbage:2020-05-03","curie:2020-05-03","davinci:2020-05-03","if-davinci-v2","if-curie-v2","if-davinci:3.0.0","davinci-if:3.0.0","davinci-instruct-beta:2.0.0","text-ada:001","text-davinci:001","text-curie:001","text-babbage:001"]'
                return ($data | ConvertFrom-Json)
            }
        }
    }
```
but tests calling the `Set-OpenAIModel` still fail with the `Incorrect API key provided` message... Will try few other things, but open to suggestions!

**Comment by SP3269** [comment]
Had a bit of thinking about this, @dfinke. So, the options are:
* Drop argument verification with `Get-OpenAIModel`. Either not verify the parameter, or introduce the list that is correct today;
* Drop the unit tests for `Set-OpenAIModel`;
* Drop the idea of `Set-OpenAIModel`. Add the parameter to `ai` and manage the default parameter using `$PSDefaultParameterValues`. Update the documentation accordingly.

I like the latter approach because that can also apply to the `chat` function. 

I understand that changing the model is not what many people will do, so it's OK to be opinionated and use `text-davinci-003` for `ai`, and `gpt-4` for `chat`. That works for the absolute majority of the users.

**Comment by dfinke** [comment]
Thanks! All good points. I like the `Set-OpenAIModel` idea, don't want to lose it. This is still shaking out in terms of usage and will change. More things coming from OpenAI.

Please move forward with what is easiest for now. If you do add it to the `ai` function, please could you add a "simple" test for check that the parameters exist. If you search the tests I have some examples, tweaking one of those should suffice.

**Comment by SP3269** [comment]
Updated with the minimal tests!

**Comment by dfinke** [comment]
Some things on the `-Model` param:

- The `Set-OpenAIModel` won't be called frequently.
- Is the `Get-OpenAIModel` call to OpenAI free? I think it may be.
- If so, and the perf hit is taken, it returns quickly.
    - Does it make send to make it a dynamic parameter so it can be selected?

**Comment by SP3269** [comment]
I couldn't find any indication that OpenAI charges for anything other than the [model use](https://openai.com/pricing), so it is free.

Intrigued about the idea of using dynamic parameter. Please elaborate?

**Comment by dfinke** [comment]
Thanks for checking. I didn't think it had a cost, be great to confirm. Maybe Twitter knows or I can post a question to OpenAI.

If the REST API remains performant then wherever there is a `$Model` parameter, do something like this in my PSAdvantage module:

https://github.com/dfinke/PSAdvantage/blob/3e91a816b7fc3191825829f5962f92edbd30f3fe/Public/Invoke-Advantage.ps1#L1

Then you can do `ai -model <kbd>ctrl</kbd>+<kbd>space</kbd>' and get list of models.

**Comment by SP3269** [comment]
Testing the API responses - 0.6 seconds on avg from AU to the US; proceeding with adding the optional parameter to `ai`.

**Comment by SP3269** [comment]
Thanks for the code updates @dfinke - was about to get on it!

**Comment by dfinke** [comment]
Your welcome. This brach needs to be updated from the trunk. I want to use it locally, see how it flows. The get-OpenAIModel, Get-ChatSessionOption, Set* etc

**Comment by SP3269** [comment]
Branches merged, please give it a go.
We might as well add. the `-Model` parameter to `ai` or (daresay) the chat functions. Happy to update this, raise a separate PR, or discuss - ultimately, your decision, @dfinke. Cheers! 🙂

**Comment by dfinke** [comment]
Thanks. Not going to add a add a `-model` to the chat functions. They are conversational, different payloads and interaction. The others are text-in text-out.

**Comment by SP3269** [comment]
So - should I add the parameter to `ai`, or this is ready to be merged? Thanks!

**Comment by dfinke** [comment]
I need to find time to test this out. I'd prefer the dynamic param. One problem is if you use `ai` and chose gpt4 as a model it'll fail . `ai` is wired to text-in, text-out payload. I'm not sure if I will update `ai` or figure out a way to not execute if a conversation-in, message-out payload is required.

**Comment by SP3269** [comment]
@dfinke - shall we abandon this? One can specify models to use with the latest code/functions. A handful of users who change from the defaults will find a way?

**Comment by dfinke** [comment]
@SP3269 Thanks for the PR! I'll close. Still need to see how this shakes out. Lots of changes and options. :-)

**Pull request closed without merging**
